#  Copyright � Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# This template is responsible for using an artifact docker image and pushing it to an ACR.
parameters:
  imageRepoName: ''
  environment: ''
  providerName: ''
  binFilePath: ''
  artifactName: ''
  dockerFile: ''
  dockerContext: ''

steps:
  - task: AzureCLI@1
    displayName: 'Docker Build + ACR Push'
    condition: and(succeeded(), eq('${{ parameters.providerName }}', 'Azure'))
    env:
      BIN_FILE_PATH: ${{ parameters.binFilePath }}
      IMAGE: $(CONTAINER_REGISTRY_NAME).azurecr.io/${{ parameters.imageRepoName }}-${{ parameters.environment }}:$(Build.SourceVersion)
      DOCKERFILE: ${{ parameters.dockerFile }}

    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        #!/usr/bin/env bash
        set -euo pipefail

        curl -L https://aka.ms/acr/installaad/bash | /bin/bash
        echo "Logging in to the ACR Registry"
        echo "------------------------------------"
        az acr login -n $(CONTAINER_REGISTRY_NAME)
        ls -l

        if [[ ! ${DOCKERFILE} ]]; then
          echo "[ERROR] No dockerfile defined"
          exit 1 
        else
          if ! ls -la ${DOCKERFILE}; then
            echo "[ERROR] No dockerfile"
            exit 1
          fi
        fi
        
        bin_file_name=$(basename $BIN_FILE_PATH)
        cp -v $BIN_FILE_PATH ${{ parameters.dockerContext }}

        pushd ${{ parameters.dockerContext }}

        echo "Tagging and Pushing $IMAGE to ACR for BIN $bin_file_name from $BIN_FILE_PATH"
        echo "------------------------------------"
        docker build --build-arg DIST=./$bin_file_name -t $IMAGE -f ${DOCKERFILE} .
        popd

        docker push $IMAGE
        echo "Show recent tags of repository ${{ parameters.imageRepoName }}"
        az acr repository show-tags -n $(CONTAINER_REGISTRY_NAME) --repository ${{ parameters.imageRepoName }}-${{ parameters.environment }} --top 10 --orderby time_desc
