#  Copyright � Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

#####################
# README: Defines a common set of deployment steps that the deploy stage can call into.
#####################

parameters:
  artifactName: 'drop'
  serviceName: ''
  providerName: ''
  binFilePattern: 'dist.tgz'
  integrationTestMavenGoal: 'package'
  mavenPublishJUnitResults: false
  testCoreMavenPomFile: ''
  testCoreMavenGoal: 'install'
  testCoreMavenOptions: ''
  testArtifactLocation: 'drop/deploy'
  elasticEndpoint: ''
  skipTest: ''
  dockerFile: ''
  testPythonFilePath: ''
  testPythonFile: ''
  runPythonTest: ''
  checkoutRepo: self
  cacheVersion: ''
  testAzureMavenCacheOption: ''
  dockerContext: $(System.DefaultWorkingDirectory)

steps:
  - task: Bash@3
    condition: and(succeeded(), eq('${{ parameters.providerName }}', 'Azure'))
    name: DetectBinScript
    displayName: Scan artifact for BIN dist files
    env:
      BIN_FILE_PATTERN: ${{ parameters.binFilePattern }}
    inputs:
      targetType: 'inline'
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "[INFO] Finding files with pattern ${BIN_FILE_PATTERN}"
        BIN_FILE_PATH=$( find . -type f -name "${BIN_FILE_PATTERN}" )
        echo "[INFO] BIN_FILE_PATH: $BIN_FILE_PATH"
        echo "##vso[task.setvariable variable=BIN_FILE_PATH;isOutput=true]$BIN_FILE_PATH"

  - template: acr-publish.yml
    parameters:
      environment: ${{ parameters.environment }}
      binFilePath: $(DetectBinScript.BIN_FILE_PATH)
      providerName: ${{ parameters.providerName }}
      imageRepoName: ${{ parameters.serviceName }}
      artifactName: ${{ parameters.artifactName }}
      dockerFile: ${{ parameters.dockerFile }}
      dockerContext: ${{ parameters.dockerContext }}

  - template: /devops/tasks/aks-deployment-steps.yml@TemplateRepo
    parameters:
      serviceName: ${{ parameters.serviceName }}
      providerName: ${{ parameters.providerName }}
      environment: ${{ parameters.environment }}
      chartPath: ${{ parameters.chartPath }}
      valuesFile: ${{ parameters.valuesFile }}
      hldRegPath: ${{ parameters.hldRegPath }}
      skipDeploy: ${{ parameters.skipDeploy }}
      checkoutRepo: ${{ parameters.checkoutRepo }}
  
  # No integration tests defined as for now
  # TODO: ?

  #- template: python-integration-test.yml
  #  parameters:
  #    stepName: PythonRunIntegrationTests
  #    testPythonFilePath: ${{ parameters.testPythonFilePath }}
  #    testPythonFile: ${{ parameters.testPythonFile }}
  #    runPythonTest: ${{ parameters.runPythonTest }}
