# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global-variables.yml"
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

aws-containerize:
  extends:
    - .aws
    - .aws_common_variables
    - .aws_variables
  needs: ["compile-and-unit-test"]
  stage: containerize
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - $(aws ecr get-login --no-include-email --region $AWS_ECR_REGION)
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --pull --push -f providers/aws/build-aws/Dockerfile.runtime --build-arg DIST=dist.tgz -t $AWS_IMAGE_TAG_BASE:$CI_COMMIT_SHA -t $AWS_IMAGE_TAG_BASE:latest .
  only:
    variables:
      - $AWS == '1'

aws_test:
  image:
    name: node:lts
  tags: ["osdu-medium"]
  allow_failure: true
  extends:
    - .aws_common_variables
    - .aws_variables
  stage: integration
  needs: ["aws-update-tf"]
  variables:
    AWS_COLLECTION_PATH: https://community.opengroup.org/osdu/qa/-/raw/main/Postman%20Collection/45_CICD_Reservoir_DDMS/Reservoir%20DDMS%20CI-CD%20v3.0.postman_collection_NotRun.json
    AWS_COLLECTION_ENV_PATH: https://community.opengroup.org/osdu/qa/-/raw/main/Postman%20Collection/00_CICD_Setup_Environment/aws.OSDU%20R3%20PROD%20v2.4.postman_environment.json
  before_script:
    - apt-get update && apt-get install -y jq
    - |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -q awscliv2.zip
      ./aws/install
    - !reference [.aws_variables, before_script]
    - |
      echo "AWS_COGNITO_USER_POOL_ID: $AWS_COGNITO_USER_POOL_ID";
      export AWS_TOKEN_FETCH_URL=$(aws ssm get-parameter --name /osdu/idp/${IDP_NAME}/oauth/token-uri --query Parameter.Value  --output text --region $AWS_REGION);
      export AWS_COGNITO_REFRESH_TOKEN=$(aws cognito-idp initiate-auth --auth-flow ${AWS_COGNITO_AUTH_FLOW} --client-id ${AWS_COGNITO_CLIENT_ID} --auth-parameters USERNAME=${AWS_COGNITO_AUTH_PARAMS_USER},PASSWORD=${AWS_COGNITO_AUTH_PARAMS_PASSWORD} | jq -r '.[].RefreshToken // empty');
      echo $AWS_COGNITO_REFRESH_TOKEN | wc -c
  script:
    - npm install -g newman
    - newman run $AWS_COLLECTION_PATH -e $AWS_COLLECTION_ENV_PATH --env-var "RESERVOIR_DDMS_HOST=${API_ENDPOINT}/api/reservoir-ddms/v2" --env-var "Token_Fetch_URL=$AWS_TOKEN_FETCH_URL" --env-var "grant_type=refresh_token" --env-var "refresh_token=${AWS_COGNITO_REFRESH_TOKEN}" --env-var "CLIENT_ID=${AWS_COGNITO_CLIENT_ID}" --env-var "data-partition-id=$DATA_PARTITION_ID"

  only:
    variables:
      - $AWS == '1'
