variables:
  #azure
  AZURE_SWAGGER_PATH: api/oetp-client/v2/

include:
  # pipeline logic
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  # global
  - local: "devops/osdu/global/gitlab.yml"

  # build
  - local: "devops/osdu/build/open-etp-client.yml"

  # scan
  # fossa
  - local: "devops/osdu/scanners/fossa-node.yml"

  # lint
  - local: "devops/osdu/scanners/lint-node.yml"

  # scan for secrets
  - local: "devops/osdu/scanners/scan-for-secrets-node.yml"

  # containerize
  # osdu
  - local: "devops/osdu/containerize/osdu.yml"

  # deploy
  # azure
  # Comment at first to only run build image.
  - local: "devops/azure/azure.gitlab-ci.yml"

  # aws
  # - local: "devops/osdu/cloud-providers/aws.yml"

  # gc
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"

  - local: "devops/gc/pipeline/override-stages.yml"

  # ibm
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-open-etp-client.yml"
