global:
  domain: ""
  limitsEnabled: true
  tier: ""
  autoscalingMode: "cpu"
  logLevel: "ERROR"

data:
  # Configmaps
  cloudProvider: "google"
  rdmsRestRootPath: "/api/reservoir-ddms/v2"
  rdmsRestPort: "8003"
  rdmsEtpHost: "oetp-server"
  rdmsEtpPort: "9002"
  rdmsEtpProtocol: "ws"
  logLevel: "error"
  # Deployments
  requestsCpu: "50m"
  requestsMemory: "250Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "oetp-client"
  image: ""
  imagePullPolicy: "IfNotPresent"

conf:
  appName: "oetp-client"
  configmap: "oetp-client-config"
  oetpClientSecret: "oetp-client-secret"

hpa:
  minReplicas: 1
  maxReplicas: 6
  cpu:
    utilization: 200
    scaleUpStabilizationWindowSeconds: 30
    scaleUpValue: 200
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 150
    scaleDownValue: 100
    scaleDownPeriod: 15
  requests:
    targetType: "AverageValue"
    targetValue: 16
    scaleUpStabilizationWindowSeconds: 10
    scaleUpValue: 50
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 60
    scaleDownValue: 25
    scaleDownPeriod: 60
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 12
  tokensPerFill: 12
  fillInterval: "1s"
