// This file is part of cxml, copyright (c) 2016 BusFaster Ltd.
// Released under the MIT license, see LICENSE.

import { Context } from "../xml/Context";
import { RawMemberSpec } from "../xml/MemberSpec";
import { RawTypeSpec } from "../xml/TypeSpec";
import { ImportSpec, ModuleExports, Namespace } from "../xml/Namespace";

/** Context for namespaces defined by calling register(). */
export const defaultContext = new Context();

/** Mark a namespace as seen. */

function mark(exportObj: ModuleExports, namespace?: Namespace) {
  if (!exportObj._cxml && namespace) {
    exportObj._cxml = [namespace];
    defaultContext.markNamespace(exportObj);
  }

  if (namespace) {
    exportObj._cxml[0] = namespace;
  }
}

/** Register a namespace.
 * This is called from JavaScript autogenerated by the cxsd compiler. */

export function register(
  name: string,
  exportObject: ModuleExports,
  importSpecList: ImportSpec[],
  exportTypeNameList: string[],
  rawTypeSpecList: RawTypeSpec[],
  rawMemberSpecList: RawMemberSpec[]
) {
  const namespace = defaultContext.registerNamespace(name).init(importSpecList);

  defaultContext.registerTypes(namespace, exportTypeNameList, rawTypeSpecList);
  defaultContext.registerMembers(namespace, rawMemberSpecList);

  mark(exportObject, namespace);

  for (const spec of importSpecList) {
    mark(spec[0]);
  }

  defaultContext.process();
}

/** Remove temporary structures needed to define new handlers and initialize the parser. */

export function init(strict?: boolean) {
  defaultContext.cleanPlaceholders(strict);
}
