// This file is part of cxml, copyright (c) 2016 BusFaster Ltd.
// Released under the MIT license, see LICENSE.

import { Context } from "../xml/Context";
import { RawMemberSpec } from "../xml/MemberSpec";
import { RawTypeSpec } from "../xml/TypeSpec";
import { ImportSpec, ModuleExports, Namespace } from "../xml/Namespace";

/** Context for namespaces defined by calling register(). */
export const contexts = new Map<string, Context>();
contexts.set("resqml20", new Context());
contexts.set("eml20", contexts.get("resqml20")!);
contexts.set("resqml22", new Context());
contexts.set("eml23", contexts.get("resqml22")!);
contexts.set("witsml21", new Context());
contexts.set("prodml22", new Context());
contexts.set("prodml23", new Context());
const defaultContext = new Context();

export const context = (ml: string): Context => {
  const c = contexts.get(ml);
  if (c === undefined) {
    throw new Error("invalid context");
  }
  return c ?? defaultContext;
};

/** Mark a namespace as seen. */

function mark(
  context: Context,
  exportObj: ModuleExports,
  namespace?: Namespace
) {
  if (!exportObj._cxml && namespace) {
    exportObj._cxml = [namespace];
    context.markNamespace(exportObj);
  }

  if (namespace) {
    exportObj._cxml[0] = namespace;
  }
}

/** Register a namespace.
 * This is called from JavaScript autogenerated by the cxsd compiler. */

export function register(
  context: Context,
  name: string,
  exportObject: ModuleExports,
  importSpecList: ImportSpec[],
  exportTypeNameList: string[],
  rawTypeSpecList: RawTypeSpec[],
  rawMemberSpecList: RawMemberSpec[]
) {
  const namespace = context.registerNamespace(name).init(importSpecList);

  context.registerTypes(namespace, exportTypeNameList, rawTypeSpecList);
  context.registerMembers(namespace, rawMemberSpecList);

  mark(context, exportObject, namespace);

  for (const spec of importSpecList) {
    mark(context, spec[0]);
  }

  context.process();
}

/** Remove temporary structures needed to define new handlers and initialize the parser. */

export function init(context: Context, strict?: boolean) {
  context.cleanPlaceholders(strict);
}
