{{- template "common.deployment" (list . "os-rest-to-etp-proxy-server.deployment") -}}
{{- define "os-rest-to-etp-proxy-server.deployment" -}}
## Define overrides for the service deployment resource here
{{- end -}}