{{- template "common.serviceaccount" (list . "os-rest-to-etp-proxy-server.serviceaccount") -}}
{{- define "os-rest-to-etp-proxy-server.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}