{{- template "common.serviceaccount" (list . "os-open-etp-client.serviceaccount") -}}
{{- define "os-open-etp-client.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}