{{- template "common.serviceparameters" (list . "os-rest-to-etp-proxy-server.serviceparameters") -}}
{{- define "os-rest-to-etp-proxy-server.serviceparameters" -}}
## Define overrides for the service parameters here
{{- end -}}