{{- template "common.virtualservice" (list . "os-rest-to-etp-proxy-server.virtualservice") -}}
{{- define "os-rest-to-etp-proxy-server.virtualservice" -}}
## Define overrides for the service's virtual service resource here
{{- end -}}