{{- template "common.virtualservice" (list . "os-open-etp-client.virtualservice") -}}
{{- define "os-open-etp-client.virtualservice" -}}
## Define overrides for the service's virtual service resource here
{{- end -}}