apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  RDMS_REST_MAIN_URL: {{ printf "https://osdu.%s" .Values.global.domain | quote }}
  RDMS_REST_ROOT_PATH: {{ .Values.data.rdmsRestRootPath | quote }}
  RDMS_REST_PORT: {{ .Values.data.rdmsRestPort | quote }}
  RDMS_ETP_HOST: {{ .Values.data.rdmsEtpHost | quote }}
  RDMS_ETP_PORT: {{ .Values.data.rdmsEtpPort | quote }}
  RDMS_ETP_PROTOCOL: {{ .Values.data.rdmsEtpProtocol | quote }}
  CLOUD_PROVIDER: {{ .Values.data.cloudProvider | quote }}
  GOOGLE_LOG_LEVEL: {{ .Values.data.logLevel | quote }}
