apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    type: ddms
    source: typescript
spec:
  replicas: {{ .Values.conf.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.conf.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.conf.appName | quote }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - image: {{ .Values.data.image | quote }}
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
        name: {{ .Values.conf.appName | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Values.conf.configmap | quote }}
        - secretRef:
            name: {{ .Values.conf.oetpClientSecret | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        resources:
          requests:
            cpu: {{ .Values.data.requestsCpu | quote }}
            memory: {{ .Values.data.requestsMemory | quote }}
          {{- if .Values.global.limitsEnabled }}
          limits:
            cpu: {{ .Values.data.limitsCpu | quote }}
            memory: {{ .Values.data.limitsMemory | quote }}
          {{- end }}
        ports:
        - containerPort: 8003
      serviceAccountName: {{ .Values.data.serviceAccountName | quote }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
