variables:
  CIMPL_SERVICE: "oetp-client"
  COLLECTION_PATH: "Postman%20Collection/45_CICD_Reservoir_DDMS/Reservoir%20DDMS%20CI-CD%20v3.0.postman_collection_NotRun.json"
  CIMPL_SUPPORTED_PLATFORM: "linux/amd64"
  DATA_PARTITION_ID: "osdu"
  CIMPL_DNS_NAME: "osdu.$CIMPL_DOMAIN"
  CIMPL_HELM_DEPLOYMENT_DIR: "devops/core-plus/deploy"
  CIMPL_HELM_PACKAGE_NAME: "cimpl-$CIMPL_SERVICE-deploy"

cimpl-containerize-gitlab:
  tags: ["osdu-medium"]
  needs: ["compile-and-unit-test"]
  variables:
    CIMPL_BUILD_PATH: "devops/core-plus/deploy/Dockerfile"
    CIMPL_BUILD_ARGS: "--build-arg DIST=dist.tgz"

cimpl-containerize-bootstrap-gitlab:
  needs: []


.cimpl_postman_tests:
  script:
    - export GET_COLLECTION_URL="${CIMPL_COLLECTION_HOST}/${CIMPL_COLLECTION_BRANCH}/${COLLECTION_PATH}?inline=false"
    - echo "Get a collection from ${GET_COLLECTION_URL}"
    - >
      if [[ -v TEST_SOURCE_FILES_DIR ]]; then
        wget -q -O tmp.zip "${CIMPL_COLLECTION_ARCHIVE_HOST}/${CIMPL_COLLECTION_BRANCH}/testing-master.zip?path=${TEST_SOURCE_FILES_DIR}" \
        && unzip -j tmp.zip \
        && rm tmp.zip
      fi
    - >
      echo "[{ \"CLIENT_ID\": \"${CIMPL_CLIENT_ID}\", \"CLIENT_SECRET\": \"${CIMPL_CLIENT_SECRET}\", \"grant_type\": \"${CIMPL_GRANT_TYPE}\", \"refresh_token\": \"${CIMPL_REFRESH_TOKEN}\"}]" > test_config_file.json
    - curl "${GET_COLLECTION_URL}" > collection.json && COLLECTION=collection.json
    - |
      curl --header "data-partition-id: ${DATA_PARTITION_ID}" "${CIMPL_POSTMAN_ENV_URL}" > environment.json && ENVIRONMENT=environment.json
    - newman run "$COLLECTION" --working-dir . -e "${ENVIRONMENT}" -d  test_config_file.json --delay-request 3000 --env-var TENANT_ID=${CIMPL_TENANT} --env-var HOSTNAME=${CIMPL_DNS_NAME} --env-var RESERVOIR_DDMS_HOST=${CIMPL_DNS_NAME}/api/reservoir-ddms/v2 --env-var Token_Fetch_URL=https://keycloak.${CIMPL_DOMAIN}/realms/osdu/protocol/openid-connect/token || exit $?
    
cimpl-test:
  tags: ["osdu-small"]
  stage: integration
  image: community.opengroup.org:5555/osdu/platform/deployment-and-operations/base-containers-cimpl/image-for-postman-tests/osdu-cimpl-image-for-postman:df5a6d3c
  allow_failure: false
  retry: 1
  extends:
    - .cimpl-variables
  script:
    - !reference [.cimpl_postman_tests, script]

cimpl-acceptance-test:
  extends:
    - .cimpl-variables

# dev2

cimpl-dev2-test:
  tags: ["osdu-small"]
  stage: integration
  image: community.opengroup.org:5555/osdu/platform/deployment-and-operations/base-containers-cimpl/image-for-postman-tests/osdu-cimpl-image-for-postman:df5a6d3c
  allow_failure: false
  retry: 1
  extends:
    - .cimpl-dev2-variables
  script:
    - !reference [.cimpl_postman_tests, script]

cimpl-dev2-acceptance-test:
  extends:
    - .cimpl-dev2-variables

cimpl-dev2-acceptance-test-python:
  extends:
    - .cimpl-dev2-variables