rdms_rest_lint:
  image: node:22.22.1
  tags: ["osdu-small"]
  stage: scan
  needs: ["compile-and-unit-test"]
  script:
    - npm install
    - npm run lint
  only:
    changes:
      - devops/**/*
      - src/**/*
    refs:
      - branches
      - main
      - merge_requests
