rdms_rest_scan-for-secrets:
  # pragma: allowlist nextline secret
  image: community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/seismic/seismic-dms-suite/seismic-store-service/seismic-store-service-detect-secrets:latest
  tags: ["osdu-small"]
  stage: scan
  needs:
    - job: compile-and-unit-test
      artifacts: false
  script:
    - >-
      detect-secrets-hook --exclude-files npm-shrinkwrap.json --exclude-files package.json
      --exclude-files devops/osdu/scanners/scan-for-secrets-node.yml 
      --exclude-files devops/azure/chart/templates/configmap.yaml 
      --exclude-files devops/azure/chart/templates/deployment.yaml
      --exclude-files devops/azure/chart/values.yaml
      --exclude-files devops/gc/deploy/values
      --exclude-files devops/core-plus/deploy/values
      --baseline devops/osdu/scanners/detect_secrets/.secrets.baseline $(git ls-files)
  only:
    changes:
      - devops/**/*
      - src/**/*
    refs:
      - branches
      - main
      - merge_requests
