{{- $namespace := .Release.Namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap }}
  namespace: {{ $namespace }}
data:
  # Azure specific
  CLOUD_PROVIDER: azure
  AZURE_LOG_LEVEL: INFO
  RDMS_ETP_PROTOCOL: "ws"
  RDMS_ETP_HOST: oetp
  RDMS_ETP_PORT: "9002"
  RDMS_ETP_PATH: ""
  # RDMS REST settings
  {{- with index .Values.configuration 0 }}
  RDMS_REST_ROOT_PATH: {{ .pathPrefix }}
  {{- end }}

  RDMS_REST_MAIN_URL: https://{{ .Values.ingress.hosts.host | default "localhost" }}
  RDMS_REST_PORT: "8003"
  OPEN_API_PORT: "443"
  RDMS_REST_SERVER_PATH: "/api/reservoir-ddms/v2/"
  
  RDMS_AUTHENTICATION_KEY_BASE: 0000000-0000-0000-0000-000000000000
  RDMS_OSDU_URL: https://{{ .Values.ingress.hosts.host | default "localhost" }}
  # Secret for ETP connection
  RDMS_JWT_SECRET: osdu-rddms

