{{- $namespace := .Release.Namespace }}
{{- $serviceType := .Values.service.type }}
{{- $servicePort := .Values.service.port }}
{{- $servicePortTarget := .Values.service.target }}
{{- $release := .Release.Name }}
{{- range .Values.configuration }}

# Copyright 2022 EPAM Systems
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  annotations:
{{ include "reservoir-ddms.commonAnnotations" . | indent 4}}
  labels:
    app: {{ .service }}
  name: {{ .service }}
  namespace: {{ $namespace }}
spec:
  type: {{ $serviceType }}
  ports:
  - name: http
    port: {{ $servicePort }}
    targetPort: {{ $servicePortTarget }}
    protocol: TCP
  selector:
    app: {{ .service }}
---
{{- end }}
