# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: /osdu/devops/docker_credentials:username
    DOCKER_PASSWORD: /osdu/devops/docker_credentials:password
    SONAR_USERNAME: /osdu/devops/sonar_credentials:username
    SONAR_PASSWORD: /osdu/devops/sonar_credentials:password

  parameter-store:
    SONAR_URL: /osdu/devops/sonar_url
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      # fix error noted here: https://github.com/yarnpkg/yarn/issues/7866
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update -y
      - export AWS_ACCOUNT_ID=`aws sts get-caller-identity | grep Account | cut -d':' -f 2 | cut -d'"' -f 2`
      - aws codeartifact login --tool npm --domain osdu-dev --domain-owner ${AWS_ACCOUNT_ID} --repository osdu-npm
      - npm install -g npm@11.3.0
      - npm install
      - wget -nv https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472.zip
      - unzip -q ./sonar-scanner-cli-4.6.2.2472.zip

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS  --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - export OUTPUT_DIR="dist"
      - export BRANCH_NAME=`echo ${BRANCH_NAME} | awk '{gsub("refs/heads/","");gsub("\\.","-");gsub("[[:space:]]","-")}1' | sed 's/\//-/g' | awk '{print tolower($0)}'`
      - export ECR_TAG_BUILDER=`echo build.builder.${BRANCH_NAME}.${CODEBUILD_BUILD_NUMBER}.${COMMIT_ID} | cut -c 1-120`
      - export ECR_TAG_PROD=`echo build.${BRANCH_NAME}.${CODEBUILD_BUILD_NUMBER}.${COMMIT_ID} | cut -c 1-120`
      - export ECR_IMAGE_BUILDER=${ECR_REGISTRY}:${ECR_TAG_BUILDER}
      - export ECR_IMAGE_PROD=${ECR_REGISTRY}:${ECR_TAG_PROD}
      - export ECR_IMAGE_BRANCH_LATEST=${ECR_REGISTRY}:${BRANCH_NAME}
      - export INTEGRATION_TEST_OUTPUT=${OUTPUT_DIR}/testing/integration
      - export INTEGRATION_TEST_OUTPUT_BIN=${INTEGRATION_TEST_OUTPUT}/bin
      - mkdir -p ${OUTPUT_DIR}/bin
      - mkdir -p ${OUTPUT_DIR}/testing && mkdir -p ${INTEGRATION_TEST_OUTPUT}  && mkdir -p ${INTEGRATION_TEST_OUTPUT}/bin
      - echo "Placeholder" >> ${OUTPUT_DIR}/build-info.json # touched so that the output directory has some content incase the build fails so that testing reports are uploaded
      - echo "Building open-etp-client"
      - npm run build:quick && npm run openAPI
      - npm run test:cov Common providers/TestAws ResponseHandlers
      - tar -czf dist.tgz dist node_modules package*
      - |
        java -jar sonar-scanner-4.6.2.2472/lib/sonar-scanner-cli-4.6.2.2472.jar \
          -Dsonar.projectKey=os-open-etp-client \
          -Dsonar.host.url=${SONAR_URL} \
          -Dsonar.login=${SONAR_USERNAME} \
          -Dsonar.password=${SONAR_PASSWORD} \
          -Dsonar.branch.name=${BRANCH_NAME} \
          -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
          -Dsonar.sources=./src/lib/providers/aws \
          -Dsonar.coverage.exclusions=**/examples/*,**/__tests__/*,**/__azure__/*,**/__google__/* \
          -Dsonar.typescript.tsconfigPath=./providers/aws/build-aws/tsconfig.json

      - echo "Build and push docker image..."
      - docker buildx create --driver docker-container --use
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/arm64/v8,linux/amd64 --pull --push --build-arg DIST=dist.tgz -f providers/aws/build-aws/Dockerfile.runtime -t ${ECR_IMAGE_PROD} -t ${ECR_IMAGE_BRANCH_LATEST} .

      - echo "Generate build-info.json"
      - |
        python providers/aws/build-aws/build-info.py \
        --branch ${BRANCH_NAME} \
        --commitId ${COMMIT_ID} \
        --commitMessage "\"${COMMIT_MESSAGE}\"" \
        --commitAuthor "\"${COMMIT_AUTHOR}\"" \
        --commitDate "\"${COMMIT_DATE}\"" \
        --buildid ${CODEBUILD_BUILD_ID} \
        --buildnumber ${CODEBUILD_BUILD_NUMBER} \
        --reponame ${REPO_NAME} \
        --outdir ${OUTPUT_DIR} \
        --artifact ${ECR_IMAGE_PROD}

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  name: ${BRANCH_NAME}/${PACKAGE_NAME}.zip
