#  Copyright © Microsoft Corporation
#  Copyright © EPAM Systems
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# Use original file: https://community.opengroup.org/osdu/platform/deployment-and-operations/helm-charts-azure/-/blob/master/osdu-ddms/README.md
# WARN: EPAM confidential not share these value

global:
  replicaCount: 2
  nodepool: services
  isAutoscalingEnabled: false

################################################################################
# Specify the azure environment specific values
## WARN: EPAM confidential not share these values
azure:
  tenant: #{AZURE_DEPLOY_SUBSCRIPTION}#
  subscription: #{AZURE_DEPLOY_SUBSCRIPTION}#
  resourcegroup: #{AZURE_TENANT_ID}#
  identity: #{AZURE_IDENTITY}#
  identity_id: #{AZURE_IDENTITY_ID}#
  keyvault: #{KEYVAULT_URI}#
  appid: #{TF_VAR_aad_client_id}#
  corsEnabled: false
  suthEnvoyFilterEnabled: false
  oidAuthEnabled: false # set this to true if you want to use oid instead of unique_name and upn

################################################################################
# Specify the Ingress Settings
#
ingress:
  enabled: true
  extraAnnotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "300"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    cert-manager.io/cluster-issuer: letsencrypt-appgw
    cert-manager.io/acme-challenge-type: http01

  #tlsSecret: osdu-certificate
  hosts:
    host: #{DNS_HOST}#
    pathPrefix: /oetp/v1/client

################################################################################
# Specify the Pod Identity
#
identity:
  name: osdu-identity


################################################################################
# Specify the Service Settings
#
service:
  type: ClusterIP
  port: 9002
  target: 9002


################################################################################
# Specify the Config Map
#
configMap: reservoir-svc-config

################################################################################
# Specify the OSDU Services to Load
#
configuration:

  ########################
  ##  RESERVOIR DDMs
  #
  - service: oetp-client
    probe:
      enabled: true
    repository: #{ACR_NAME}#.azurecr.io/#{AZURE_SERVICE}#
    tag: #{ACR_IMAGE_TAG}#
    keyvault: true
    pathPrefix: /oetp/reservoir-ddms
    auth:
      disable:
        - "/"
        - "/.well-known/etp-server-capabilities"
    env:
    - name: SERVICE_NAME
      value: #{AZURE_SERVICE}#
    - name: KEYVAULT_URL
      config:
        name: osdu-svc-config
        key: ENV_KEYVAULT
    - name: AZ_AI_INSTRUMENTATION_KEY
      secret:
        name: central-logging
        key: appinsights

################################################################################
# Specify pod annotations
#
annotations:
  commitId: ""
