include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

azure_containerize:
  needs: ["compile-and-unit-test"]
  script:
    - |
      docker build \
      --build-arg DIST=dist.tgz \
      --file devops/osdu/docker/Dockerfile.runtime \
      -t $CI_REGISTRY_IMAGE/$SHA_IMAGE \
      -t ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE \
      -t ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE .
    - az acr login -n $AZURE_REGISTRY
    - docker push ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE
    - docker push ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE
    - |
      if [ ! -z "$CI_COMMIT_TAG" ]; then
        docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
        docker push ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
      fi
      echo "AZURE_REGISTRY_TOKEN=$(az acr login -n $AZURE_REGISTRY --expose-token --query 'accessToken' -otsv)" >> acr_tokens.env
      echo "DST_REGISTRY_TOKEN=$(az acr login -n msosdu --expose-token --query 'accessToken' -otsv)" >> acr_tokens.env

azure_containerize_helm:
  needs: ["compile-and-unit-test"]
  stage: containerize
  variables:
    AZURE_HELM_SUBDIR: osdu-ddms/standard-ddms

azure_deploy:
  script:
    # Install or Upgrade Service
    - helm show chart $HELM_CHART_OCI --version $HELM_CHART_OCI_VERSION
    - ENV_VAULT=$(kubectl get cm -n osdu osdu-svc-config -o jsonpath={.data.ENV_KEYVAULT} | sed -e 's/https:\/\///;s/.vault.azure.*//')
    - kubectl delete deploy -l app=oetp-client -n osdu
    - >-
      helm upgrade -i osdu-gitlab-$CI_PROJECT_NAME $HELM_CHART_OCI --version $HELM_CHART_OCI_VERSION -n osdu --wait --timeout 5m
      -f devops/azure/reservoir.values.yaml
      --set azure.tenant=$AZURE_TENANT_ID
      --set azure.subscription=$AZURE_SUBSCRIPTION_ID
      --set azure.resourcegroup=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/base-name-cr --query value -otsv)-rg
      --set azure.identity=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/base-name-cr --query value -otsv)-osdu-identity
      --set azure.identity_id=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/osdu-identity-id --query value -otsv)
      --set azure.keyvault.name=$ENV_VAULT
      --set azure.acr=${AZURE_REGISTRY}.azurecr.io
      --set configuration[0].container.image=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
      --set configuration[0].container.tag=${CI_COMMIT_SHA} --set configuration[0].config.RDMS_JWT_SECRET="osdu-rddms"
      --set ingress.dns=$AZURE_DNS_NAME
    - POD_SERVICE_NAME=oetp-client
    - pod=$(kubectl get pod -n osdu|grep $POD_SERVICE_NAME |tail -1 |awk '{print $1}') || echo "[WARN] Not able to get pod but helm upgrade was successful"
    - status=$(kubectl wait -n osdu --for=condition=Ready pod/$pod --timeout=300s)
    - if [[ "$status" != *"met"* ]]; then echo "POD didn't start correctly" ; exit 1 ; fi
    - |
      echo "AZURE_REGISTRY_TOKEN=$(az acr login -n $AZURE_REGISTRY --expose-token --query 'accessToken' -otsv)" >> ${CI_PROJECT_DIR}/acr_tokens.env
      echo "DST_REGISTRY_TOKEN=$(az acr login -n msosdu --expose-token --query 'accessToken' -otsv)" >> ${CI_PROJECT_DIR}/acr_tokens.env
  artifacts:
    reports:
      dotenv: ${CI_PROJECT_DIR}/acr_tokens.env

azure_test:
  image:
    name: postman/newman:alpine
    entrypoint: [""]
  stage: integration
  tags: ["osdu-small"]
  needs: ["azure_deploy"]
  extends: .azure_variables
  variables:
    AZURE_POSTMAN_COLLECTION_FILE_URL: $AZURE_POSTMAN_COLLECTION_FILE_URL
    AZURE_POSTMAN_ENVIRONMENT_FILE_URL: $AZURE_POSTMAN_ENVIRONMENT_FILE_URL
    AZURE_CLIENT_ID: $AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
    AZURE_REFRESH_TOKEN: $AZURE_REFRESH_TOKEN
  script:
    - newman --version
    - newman run ${AZURE_POSTMAN_COLLECTION_FILE_URL} -e ${AZURE_POSTMAN_ENVIRONMENT_FILE_URL} --env-var TENANT_ID=${AZURE_TENANT_ID} --env-var CLIENT_ID=${AZURE_CLIENT_ID} --env-var CLIENT_SECRET=${AZURE_CLIENT_SECRET} --env-var HOSTNAME=${AZURE_DNS_NAME} --env-var refresh_token=${AZURE_REFRESH_TOKEN} --env-var RESERVOIR_DDMS_HOST=${AZURE_DNS_NAME}/api/reservoir-ddms/v2
  only:
    refs:
      - branches
      - main
      - merge_requests
      - tags
  allow_failure: true
  except:
    variables:
      - $AZURE_SKIP_TEST == 'true'

# It is a temporary change as azure_code_coverage not yet been implemented for CPP services.
# Therefore the job has been disabled
azure_code_coverage:
  needs: ["compile-and-unit-test"]
  extends:
    - .azure_variables
  variables:
    AZURE_SKIP_COVERAGE: "true"

azure_test_py:
  extends:
    - .azure_variables
  before_script:
    - ""
  script:
    - echo "No test_py for nodejs"

azure-acceptance-test:
  extends:
    - .azure_variables
