include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

azure_containerize:
  needs: ["rdms_rest_compile-and-unit-test"]
  script:
    - |
      docker build \
      --build-arg DIST=dist.tgz \
      --file devops/osdu/docker/Dockerfile.runtime \
      -t $CI_REGISTRY_IMAGE/$SHA_IMAGE \
      -t ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE \
      -t ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE .
    - az acr login -n $AZURE_REGISTRY
    - docker push ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE
    - docker push ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE
    - |
      if [ ! -z "$CI_COMMIT_TAG" ]; then
        docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
        docker push ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
      fi

azure_test:
  image: $CI_REGISTRY_IMAGE/$SHA_IMAGE
  stage: integration
  needs: ["azure_deploy"]
  allow_failure: true
  retry: 1
  extends:
    - .azure_variables
  script: 
    - echo "TODO"

azure_code_coverage:
  extends:
    - .azure_variables
  allow_failure: true
  before_script:
    - ""
  script:
    - echo "TODO FOR AZURE"

azure_deploy:
  script:
    # Install Service
    - helm uninstall osdu-gitlab-$CI_PROJECT_NAME -n osdu && sleep 60
    - >-
      helm upgrade -i osdu-gitlab-$CI_PROJECT_NAME devops/azure/chart/ -f devops/azure/chart/values.yaml -n osdu
      --set ingress.hosts.host=${AZURE_DNS_NAME}
      --set configuration[0].repository=${AZURE_REGISTRY}.azurecr.io/${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
      --set configuration[0].tag=${CI_COMMIT_SHA}
      --set configuration[0].env[1].config.name=osdu-svc-properties
    # Increasing to 900s as rolling updates are happening and each service is expected to have minimum 2 containers.
    - kubectl rollout status deployment.v1.apps/osdu-gitlab-$CI_PROJECT_NAME-oetp-client -n osdu --timeout=200s || echo "[WARN] No success deploy"
    - kubectl get -n osdu deployment.v1.apps/osdu-gitlab-$CI_PROJECT_NAME-oetp-client || echo "[WARN] Not able to get deploy"    
    - kubectl get pods -n osdu | grep ${CI_PROJECT_NAME}
    - for PP in $(kubectl get pod -n osdu | grep $CI_PROJECT_NAME | awk '{print $1}'); do kubectl -n osdu describe pod ${PP} | grep Events -A20; kubectl logs pod/${PP} -n osdu -c oetp-client --tail 20; done
    - kubectl get ingress -n osdu osdu-gitlab-${CI_PROJECT_NAME}-ingress || echo "[WARN] Not able to get ingress"
    - status=$(kubectl wait -n osdu --for=condition=Ready pod/$pod --timeout=300s)
    - if [[ "$status" != *"met"* ]]; then echo "POD didn't start correctly" ; exit 1 ; fi

azure_test_py:
  extends:
    - .azure_variables
  before_script:
    - ""
  script:
    - echo "No test_py for nodejs"
