# WARNING if you hadn't setup your agent, most likely this stage will fail

parameters:
  - name: checkoutRepo
    default: self
  - name: buildDir
    default: $(System.DefaultWorkingDirectory)
  - name: copyFileContents
    default: '**dist.tgz**'
  - name: useDockerBuildOnly
    default: 'true'

# https://github.com/microsoft/azure-pipelines-agent/issues/2043#issuecomment-687983301
stages:
  - stage: 'Build'
    #condition: ne(${{ parameters.useDockerBuildOnly }}, 'true')
    variables: 
      artifactName: 'drop'
    jobs:
      - job: Build_Npm
        displayName: Npm Build
        pool: 
          vmImage: ubuntu-20.04
        workspace:
          clean: all
        steps:
          - download: none
          - checkout: ${{ parameters.checkoutRepo }}
            persistCredentials: 'true'

          #- task: Cache@2
          #  inputs:
          #    key: '${{ parameters.buildDir }} | "$(Agent.OS)"'
          #    path: $(System.DefaultWorkingDirectory)/${{ parameters.buildDir }}
          #  displayName: Cache for npm build
          
          # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm?view=azure-devops
          - task: Npm@1
            displayName: 'Npm Install'
            inputs:
              command: install # Required. Command. Default: install
              workingDir: $(System.DefaultWorkingDirectory) # Working folder that contains package.json. 

          - task: Npm@1
            displayName: 'Npm Build'
            inputs:
              command: custom # Required. Command. Default: install
              workingDir: $(System.DefaultWorkingDirectory) # Working folder that contains package.json. 
              customCommand: run build # Required when command = custom. Command and arguments. 

          - script: |
              ls
              tar -cvzf ${{ parameters.buildDir }}/dist.tgz dist node_modules package*
              du -sh dist.tgz
            displayName: 'Packaging dependencies'

          - task: CopyFiles@2
            displayName: 'Copy artifacts for node deploy to: $(build.artifactstagingdirectory)'
            inputs:
              SourceFolder: ${{ parameters.buildDir }}
              Contents: ${{ parameters.copyFileContents }}
              TargetFolder: '$(build.artifactstagingdirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: dist.tgz'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              ArtifactName: '${{ variables.artifactName }}'
              publishLocation: 'Container'
            condition: succeededOrFailed()