#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# ingress:
#   dns: <ingress_dns>
#   # This will not install istio virtual service but AGIC ingress instead
#   appGateway:
#     issuer: letsencrypt-prod-dns
#     enableKeyvaultCert: false
#   annotations:
#     appgw.ingress.kubernetes.io/backend-path-prefix: "/"

deployment:
  replicaCount: 1

configuration:
  ####################
  # RESERVOIR CLIENT #
  ####################
  - service: "oetp-client"
    container:
      image: open-etp-client
      containerPort: 8003
    path: /api/reservoir-ddms/v2/
    pathRewrite: "/"
    probe:
      readiness:
        path: /
      liveness:
        path: /metrics
    auth:
      disable:
        - "/swagger*"
        - "/metrics"
        - "/"
    config:
      RDMS_ETP_HOST: "oetp-service"
      RDMS_ETP_PORT: "80"
      RDMS_REST_ROOT_PATH: "/"
      RDMS_REST_SERVER_PATH: "/api/reservoir-ddms/v2/"
      RDMS_REST_MAIN_URL: https://{{ .Values.ingress.dns }}
      RDMS_OSDU_URL: https://{{ .Values.ingress.dns }}
      RDMS_REST_PORT: "8003"
      OPEN_API_PORT: "443"
      RDMS_AUTHENTICATION_KEY_BASE: 0000000-0000-0000-0000-000000000000
      RDMS_DATA_PARTITION_MODE: "osdu"
      RDMS_AUDIT_LOG_ENABLED: "true"
      CLOUD_PROVIDER: azure
      RDMS_ETP_PROTOCOL: "ws"
      AZURE_LOG_LEVEL: INFO
